### PR TITLE
Add Static methods to UI to allow Page to be set more easily in MVC app

### PR DESCRIPTION
**Pull request by munnster**
Hi,

Been having issues with the UI.Head() helper in passive mode, the below change allows a neater fix than what I'm currently using to get around the issue.

Let me know if I've missed something!

Cheers

Ali

### CODE REVIEW

**Comment by tidyui** [comment]
Hi! I think the reason for `UIHelper.SetCurrent` not being exposed in `Piranha.Mvc.UI` is that the implementation in UIHelper is a way to locally override the current instance. However, `Piranha.Mvc.UI` is **static** with a single instance of the UIHelper shared between all threads executing, this means setting a local variable in this single instance can produce some weird behavior.

However, Changing your implementation to setting the value in the HttpContext will be thread-safe and produce the behaviour you want:

    public static void SetCurrent(Models.Page page) { 
      HttpContext.Current.Items["Piranha_CurrentPage"] = page;
    }

    public static void SetCurrent(Models.Post post) { 
      HttpContext.Current.Items["Piranha_CurrentPost"] = post;
    }

I can merge your pull request and make the modifications if you like!

**Comment by tidyui** [comment]
I merged your PR and updated it according to the comments. Thanks for sharing! Just keep the pull requests coming :)

Regards

**Comment by munnster** [comment]
Ah, that's cool. Didn't realise that, thanks for approving my 1st PR :)

Ali

**Comment by tidyui** [comment]
No problems! Contributing should be fun, not some bald guy nagging about petty things ;)

**Pull request merged**
